<script lang="ts">
  import { Button, Modal } from 'svelte-pieces'
  import { page } from '$app/stores'

  export let on_close: () => void
  // export let entry: EntryData
  export let image_file = undefined
  let author_connection = ''

  const upload_triggered = false
  $: ({ admin, dbOperations, url_from_storage_path } = $page.data)
  let readyToRecord: boolean

  let file: File
  let audioBlob: Blob

  // $: if (image_file) {
  //   file = undefined
  //   audioBlob = undefined
  // }

  $: initial_speaker_id = image_file?.speakers?.[0].id

// function startUpload(speaker_id: string): Readable<AudioVideoUploadStatus> {
  //   const uploadStore = dbOperations.addAudio({
  //     file: file || audioBlob,
  //     entry_id: entry.id,
  //     speaker_id,
  //   })

  //   const unsubscribe = uploadStore.subscribe((status) => {
  //     if (status?.progress === 100) {
  //       upload_triggered = true
  //       unsubscribe()
  //     }
  //   })

  //   return uploadStore
  // }
</script>

<Modal on:close={on_close}>
  <label class="button-label">
    <input
      type="file"
      accept="image/*"
      class="hidden"
      on:input={(e) => {
        // @ts-ignore
        handleImage(e.target.files)
      }} />

    <i class="far fa-upload" />&nbsp;
    Upload Image
  </label>

  <div class="mb-6" />

  <label class="block mb-2 text-sm font-medium text-gray-700" for="authorConnection">
    Image Attrbution / Source of the image (required)
  </label>
  <textarea
    name="authorConnection"
    required
    rows="1"
    minlength="100"
    maxlength="2500"
    bind:value={author_connection}
    class="form-input w-full" />
  <div class="flex text-xs">
    <div class="text-gray-500 ml-auto">{author_connection.length}/2500</div>
  </div>
  <div>
    <input type="checkbox" id="rigths" name="rigths" required />
    <label for="rigths">I have the rights to use this image</label>
  </div>
  <div>
    <input type="checkbox" id="ai_image" name="ai_image" />
    <label for="ai_image">This image is generated by AI</label>
  </div>

  <!-- <SelectSpeaker
    initialSpeakerId={initial_speaker_id}
    let:speaker_id
    {select_speaker}>
    {#if image_file}
      <div class="px-1">
        <Waveform audioUrl={url_from_storage_path(image_file.storage_path)} />
      </div>
    {:else if speaker_id}
      {#if file || audioBlob}
        {#if file}
          <Waveform audioUrl={URL.createObjectURL(file)} />
        {:else}
          <Waveform {audioBlob} />
        {/if}
        <div class="mb-3" />
        {#if !upload_triggered && (file || audioBlob)}
          {@const upload_status = startUpload(speaker_id)}
          {#await import('$lib/components/audio/UploadProgressBarStatus.svelte') then { default: UploadProgressBarStatus }}
            <UploadProgressBarStatus {upload_status} />
          {/await}
        {/if}
      {:else}
        <div class="flex flex-col">
          <div class="mb-2">
            <RecordAudio bind:audioBlob bind:permissionGranted={readyToRecord} />
          </div>
          {#if !readyToRecord}
            <SelectAudio bind:file />
          {/if}
        </div>
      {/if}
    {/if}
  </SelectSpeaker> -->

  <div class="modal-footer">
    <!-- {#if image_file}
      {#if $admin > 1}
        <JSON obj={image_file} />
        <div class="w-1" />
      {/if}

      <Button
        href={url_from_storage_path(image_file.storage_path)}
        target="_blank">
        <i class="fas fa-download" />
        <span class="hidden sm:inline">{$page.data.t('misc.download')}</span>
      </Button>
      <div class="w-1" />

      <Button
        onclick={async () => {
          const confirmation = confirm($page.data.t('entry.delete_audio'))
          if (confirmation) await dbOperations.update_audio({ deleted: new Date().toISOString(), id: image_file.id })
          on_close()
        }}
        color="red">
        <i class="far fa-trash-alt" />&nbsp;
        <span class="hidden sm:inline">{$page.data.t('misc.delete')}</span>
      </Button>
      <div class="w-1" />
    {/if} -->

    <Button onclick={on_close} color="black">
      {$page.data.t('misc.close')}
    </Button>
  </div>
</Modal>

<style>
  .button-label {
    --at-apply: flex justify-center items-center px-3 py-2 border font-medium
  cursor-pointer focus:outline-none border-green-300
  focus:ring focus:ring-green-300 active:bg-green-200 transition ease-in-out
  duration-150 rounded hover:bg-green-100 text-green-700;
  }

.dragging {
    --at-apply: bg-green-200 border-green-300 text-green-800 border-dashed;
  }
</style>
