<script lang="ts">
  import { Button, Modal } from 'svelte-pieces'
  import { setContext } from 'svelte'
  import { page } from '$app/stores'
  import AddImage from '$lib/components/image/AddImage.svelte'

  setContext('applyButtonLabel', true)

  export let on_close: () => void
  export let first_sense_id: string
  let author_connection = ''
  let rights = false
  let ai_image = false

  $: ({ dbOperations } = $page.data)

</script>

<Modal on:close={on_close}>
  {#if author_connection.length > 10 && rights}
    <AddImage upload_image={file => dbOperations.addImage({ file, sense_id: first_sense_id })}>
      <div class="text-xs">
        {$page.data.t('entry_field.photo')}
      </div>
    </AddImage>
  {/if}

  <div class="mb-6" />

  <label class="block mb-2 text-sm font-medium text-gray-700" for="authorConnection">
    Image Attribution / Source of the image (required)
  </label>
  <textarea
    name="authorConnection"
    required
    rows="4"
    minlength="100"
    maxlength="2500"
    bind:value={author_connection}
    class="form-input w-full" />
  <div class="flex text-xs">
    <div class="text-gray-500 ml-auto">{author_connection.length}/2500</div>
  </div>
  <div>
    <input bind:checked={rights} type="checkbox" id="rigths" name="rigths" required />
    <label for="rigths">I have the rights to upload this image file</label>
  </div>
  <div>
    <input bind:checked={ai_image} type="checkbox" id="ai_image" name="ai_image" />
    <label for="ai_image">This image was generated by AI</label>
  </div>

  <div class="modal-footer">
    <!-- {#if image_file}
      {#if $admin > 1}
        <JSON obj={image_file} />
        <div class="w-1" />
      {/if}

      <Button
        href={url_from_storage_path(image_file.storage_path)}
        target="_blank">
        <i class="fas fa-download" />
        <span class="hidden sm:inline">{$page.data.t('misc.download')}</span>
      </Button>
      <div class="w-1" />

      <Button
        onclick={async () => {
          const confirmation = confirm($page.data.t('entry.delete_audio'))
          if (confirmation) await dbOperations.update_audio({ deleted: new Date().toISOString(), id: image_file.id })
          on_close()
        }}
        color="red">
        <i class="far fa-trash-alt" />&nbsp;
        <span class="hidden sm:inline">{$page.data.t('misc.delete')}</span>
      </Button>
      <div class="w-1" />
    {/if} -->

    <Button onclick={on_close} color="black">
      {$page.data.t('misc.close')}
    </Button>
  </div>
</Modal>
