import type { SentenceToken } from '$lib/db/schemas/dictionary.types'
import { is_punctuation_form, normalized_word_key } from './tokenize-sentence'

/**
 * Re-tokenize preservation (.issues/texts-sentences-pipeline.md M3): after a
 * sentence's text changes, carry links/glosses from the PREVIOUS token array
 * onto the FRESH tokenization by normalized-form equality. Two passes: an
 * ordered greedy pass (handles insertions/deletions around stable words), then
 * a global pass for words that moved (reordered sentences). Vanished forms
 * drop their token — the caller cleans up `senses_in_sentences` for the
 * returned `dropped_sense_ids`.
 */

interface Placement {
  token: SentenceToken
  /** Index range [from, to) of the fresh tokens this placement replaces. */
  from: number
  to: number
}

function has_metadata(token: SentenceToken): boolean {
  if (token.entry_id || token.sense_id || token.gloss || token.morphemes || token.candidates)
    return true
  // Human-ignored WORDS carry over; ignored punctuation is regenerated by the tokenizer.
  return token.status === 'ignored' ? !is_punctuation_form(token.form) : token.status === 'confirmed'
}

function carry_metadata({ old_token, form, start, end }: {
  old_token: SentenceToken
  form: string
  start: number
  end: number
}): SentenceToken {
  const token: SentenceToken = { form, start, end }
  if (old_token.gloss) token.gloss = old_token.gloss
  if (old_token.morphemes) token.morphemes = old_token.morphemes
  if (old_token.entry_id) token.entry_id = old_token.entry_id
  if (old_token.sense_id) token.sense_id = old_token.sense_id
  if (old_token.candidates) token.candidates = old_token.candidates
  if (old_token.status) token.status = old_token.status
  return token
}

export function carry_over_tokens({ previous, next, text }: {
  previous: SentenceToken[]
  /** Fresh tokenization of the (possibly edited) text. */
  next: SentenceToken[]
  text: string
}): { tokens: SentenceToken[], dropped_sense_ids: string[] } {
  const carriable = previous.filter(has_metadata)
  if (!carriable.length)
    return { tokens: next, dropped_sense_ids: [] }

  const consumed = Array.from({ length: next.length }, () => false)
  const placements: Placement[] = []
  const dropped_sense_ids: string[] = []

  /** Find `key` as a run of consecutive unconsumed WORD tokens (no punctuation
   *  inside the span — same rule as the phrase matcher), searching from `from`. */
  function find_run({ key, from }: { key: string, from: number }): { from: number, to: number } | null {
    const key_words = key.split(' ').length
    for (let start_index = from; start_index < next.length; start_index++) {
      let matched_words = 0
      let scan = start_index
      let joined = ''
      while (scan < next.length && matched_words < key_words) {
        if (consumed[scan])
          break
        const word_key = normalized_word_key(next[scan].form)
        if (!word_key)
          break // punctuation token breaks the run
        joined = joined ? `${joined} ${word_key}` : word_key
        matched_words++
        scan++
      }
      if (matched_words === key_words && joined === key)
        return { from: start_index, to: scan }
    }
    return null
  }

  function place({ old_token, run }: { old_token: SentenceToken, run: { from: number, to: number } }) {
    const { start } = next[run.from]
    const { end } = next[run.to - 1]
    placements.push({
      token: carry_metadata({ old_token, form: text.slice(start, end), start, end }),
      from: run.from,
      to: run.to,
    })
    for (let index = run.from; index < run.to; index++)
      consumed[index] = true
  }

  // Pass 1 — ordered greedy from a moving cursor.
  const unplaced: SentenceToken[] = []
  let cursor = 0
  for (const old_token of carriable) {
    const key = normalized_word_key(old_token.form)
    if (!key) {
      if (old_token.sense_id) dropped_sense_ids.push(old_token.sense_id)
      continue
    }
    const run = find_run({ key, from: cursor })
    if (run) {
      place({ old_token, run })
      cursor = run.to
    } else {
      unplaced.push(old_token)
    }
  }

  // Pass 2 — words that moved earlier in the sentence.
  for (const old_token of unplaced) {
    const run = find_run({ key: normalized_word_key(old_token.form), from: 0 })
    if (run)
      place({ old_token, run })
    else if (old_token.sense_id)
      dropped_sense_ids.push(old_token.sense_id)
  }

  const placement_by_start = new Map(placements.map(placement => [placement.from, placement]))
  const tokens: SentenceToken[] = []
  for (let index = 0; index < next.length; index++) {
    const placement = placement_by_start.get(index)
    if (placement) {
      tokens.push(placement.token)
      index = placement.to - 1
    } else if (!consumed[index]) {
      tokens.push(next[index])
    }
  }
  return { tokens, dropped_sense_ids }
}

if (import.meta.vitest) {
  const confirmed = (form: string, start: number, end: number, extras: Partial<SentenceToken> = {}): SentenceToken =>
    ({ form, start, end, entry_id: 'e1', sense_id: 's1', status: 'confirmed', ...extras })

  describe(carry_over_tokens, () => {
    test('stable words keep their links across an insertion', () => {
      const previous = [confirmed('nak', 0, 3), { form: 'kaq', start: 4, end: 7 }]
      const text = 'nak wia kaq'
      const next = [
        { form: 'nak', start: 0, end: 3 },
        { form: 'wia', start: 4, end: 7 },
        { form: 'kaq', start: 8, end: 11 },
      ]
      const { tokens, dropped_sense_ids } = carry_over_tokens({ previous, next, text })
      expect(tokens).toEqual([
        confirmed('nak', 0, 3),
        { form: 'wia', start: 4, end: 7 },
        { form: 'kaq', start: 8, end: 11 },
      ])
      expect(dropped_sense_ids).toEqual([])
    })

    test('a reordered word still keeps its link (pass 2)', () => {
      const previous = [
        { form: 'wia', start: 0, end: 3 },
        confirmed('nak', 4, 7),
      ]
      const text = 'nak wia'
      const next = [
        { form: 'nak', start: 0, end: 3 },
        { form: 'wia', start: 4, end: 7 },
      ]
      const { tokens } = carry_over_tokens({ previous, next, text })
      expect(tokens).toEqual([
        confirmed('nak', 0, 3),
        { form: 'wia', start: 4, end: 7 },
      ])
    })

    test('a deleted word drops its token and reports the sense for junction cleanup', () => {
      const previous = [confirmed('nak', 0, 3), confirmed('kaq', 4, 7, { sense_id: 's2' })]
      const text = 'nak'
      const next = [{ form: 'nak', start: 0, end: 3 }]
      const { tokens, dropped_sense_ids } = carry_over_tokens({ previous, next, text })
      expect(tokens).toEqual([confirmed('nak', 0, 3)])
      expect(dropped_sense_ids).toEqual(['s2'])
    })

    test('a confirmed PHRASE token re-merges its fresh word tokens', () => {
      const previous = [confirmed('nak toré', 0, 8)]
      const text = 'wia nak toré'
      const next = [
        { form: 'wia', start: 0, end: 3 },
        { form: 'nak', start: 4, end: 7 },
        { form: 'toré', start: 8, end: 12 },
      ]
      const { tokens } = carry_over_tokens({ previous, next, text })
      expect(tokens).toEqual([
        { form: 'wia', start: 0, end: 3 },
        confirmed('nak toré', 4, 12),
      ])
    })

    test('gold IGT gloss/morphemes carry over; case/diacritic changes still match', () => {
      const previous: SentenceToken[] = [{
        form: 'Toré',
        start: 0,
        end: 4,
        gloss: { default: '3PL' },
        morphemes: [{ form: 'tor' }, { form: 'é', separator: '-' }],
      }]
      const text = 'tore nak'
      const next = [
        { form: 'tore', start: 0, end: 4 },
        { form: 'nak', start: 5, end: 8 },
      ]
      const { tokens } = carry_over_tokens({ previous, next, text })
      expect(tokens[0]).toEqual({
        form: 'tore',
        start: 0,
        end: 4,
        gloss: { default: '3PL' },
        morphemes: [{ form: 'tor' }, { form: 'é', separator: '-' }],
      })
    })

    test('human-ignored words carry; ignored punctuation is regenerated fresh', () => {
      const previous: SentenceToken[] = [
        { form: 'uh', start: 0, end: 2, status: 'ignored' },
        { form: ',', start: 2, end: 3, status: 'ignored' },
      ]
      const text = 'uh, nak'
      const next = tokens_for_uh_nak()
      const { tokens } = carry_over_tokens({ previous, next, text })
      expect(tokens).toEqual([
        { form: 'uh', start: 0, end: 2, status: 'ignored' },
        { form: ',', start: 2, end: 3, status: 'ignored' },
        { form: 'nak', start: 4, end: 7 },
      ])
    })

    test('unchanged text round-trips identically', () => {
      const previous = [confirmed('nak', 0, 3), { form: '!', start: 3, end: 4, status: 'ignored' as const }]
      const text = 'nak!'
      const next = [
        { form: 'nak', start: 0, end: 3 },
        { form: '!', start: 3, end: 4, status: 'ignored' as const },
      ]
      const { tokens, dropped_sense_ids } = carry_over_tokens({ previous, next, text })
      expect(tokens).toEqual([confirmed('nak', 0, 3), { form: '!', start: 3, end: 4, status: 'ignored' }])
      expect(dropped_sense_ids).toEqual([])
    })
  })

  function tokens_for_uh_nak(): SentenceToken[] {
    return [
      { form: 'uh', start: 0, end: 2 },
      { form: ',', start: 2, end: 3, status: 'ignored' },
      { form: 'nak', start: 4, end: 7 },
    ]
  }
}
