/**
 * Wire shape POSTed to the VPS's `/api/messages/email-inbound` endpoint.
 *
 * Duplicated (intentionally) from
 * `site/src/routes/api/messages/email-inbound/+server.ts` since `cf-worker/`
 * is a standalone deploy with its own `tsconfig.json` and doesn't share
 * modules with the SvelteKit app. The VPS-side test suite exercises this
 * same shape — drift surfaces as a 400 on the inbound endpoint, visible
 * immediately in `wrangler tail`.
 *
 * If the VPS contract changes, update both ends in the same commit.
 */

export interface AttachmentPayload {
  /** UUID generated by the worker; doubles as the R2 object key. */
  attachment_id: string
  filename: string
  mimetype: string
  size_bytes: number
  content_id?: string | null
  disposition: 'attachment' | 'inline'
}

export interface MessagesEmailInboundRequestBody {
  message_id: string
  in_reply_to: string | null
  email_references: string[]
  from_email: string
  from_name: string | null
  to_email: string
  cc?: string[]
  subject: string
  body_text: string | null
  body_html: string | null
  raw_headers: string
  received_at: string
  attachments: AttachmentPayload[]
}

export interface Env {
  LD_VPS_URL: string
  INTERNAL_INGEST_SECRET: string
  /** R2 bucket binding — attachment bytes get `.put()` here, keyed by UUID. */
  ATTACHMENTS: R2Bucket
}
