// vitest stand-in for SvelteKit's `$env/static/public` (generated by SvelteKit
// at build time). Add other PUBLIC_* values here as test import graphs need them.
export const PUBLIC_STORAGE_BUCKET = 'talking-dictionaries-dev.appspot.com'
export const PUBLIC_MODE = 'dev'
export const PUBLIC_GOOGLE_OAUTH_CLIENT_ID = ''
export const PUBLIC_mapboxAccessToken = ''
