/**
 * Vitest stand-in for `$env/static/public`. The real module is generated by
 * SvelteKit at build time; tests bypass SvelteKit entirely so they need an
 * alias to a plain TS module that exports each `PUBLIC_*` value as a const.
 *
 * Default value for `PUBLIC_MODE` is `'dev'` so callers that branch on it
 * take their dev-mode path under test. Override with
 * `vi.mock('$env/static/public', () => ({ PUBLIC_MODE: 'production' }))`
 * when a test specifically needs production behavior.
 */
export const PUBLIC_MODE = 'dev'
