import type Database from 'better-sqlite3'
import type { RequestHandler } from './$types'
import { randomUUID } from 'node:crypto'
import { env } from '$env/dynamic/private'
import { ResponseCodes } from '$lib/constants'
import { get_shared_db } from '$lib/db/server/shared-db'
import { find_or_create_thread } from '$lib/email/find-or-create-thread'
import { error, json } from '@sveltejs/kit'

/**
 * Inbound endpoint called by the LD Cloudflare Email Routing Worker after it
 * has parsed an incoming email's MIME AND uploaded each attachment directly
 * to the `livingdictionaries-attachments` R2 bucket via its bucket binding.
 * The worker POSTs metadata-only — attachment bytes never touch the VPS for
 * inbound flows.
 *
 * Authentication: shared secret `X-Internal-Secret` (same secret used by the
 * contact-form endpoint — one secret for all CF↔VPS traffic).
 *
 * Threading: see `lib/email/find-or-create-thread.ts`.
 *
 * **CF Worker setup is OUT OF SCOPE for the current session** — see
 * `.issues/admin-backend-rollout.md` D4 section for the contract and the
 * deferred items. This endpoint is fully functional once the Worker is
 * created and configured to post the documented payload.
 */

export interface AttachmentPayload {
  /** UUID generated by the worker; doubles as the R2 object key. */
  attachment_id: string
  filename: string
  mimetype: string
  size_bytes: number
  /** RFC 2392 cid for inline images (no angle brackets). */
  content_id?: string | null
  disposition: 'attachment' | 'inline'
}

export interface MessagesEmailInboundRequestBody {
  /** RFC 5322 `Message-ID:` header, full angle-bracketed form. */
  message_id: string
  /** Angle-bracketed prior `Message-ID` from `In-Reply-To:`, or null. */
  in_reply_to: string | null
  /** Each entry angle-bracketed, in chronological order, from `References:`. */
  email_references: string[]
  /** Sender's address from the `From:` header. */
  from_email: string
  from_name: string | null
  /** Which `*@livingdictionaries.app` alias the customer emailed under catch-all. */
  to_email: string
  cc?: string[]
  subject: string
  body_text: string | null
  body_html: string | null
  /** JSON-stringified header dictionary, retained for audit/debugging. */
  raw_headers: string
  /** ISO 8601 timestamp from CF Workers. */
  received_at: string
  attachments: AttachmentPayload[]
}

export interface MessagesEmailInboundResponseBody {
  ok: true
  thread_id: string
  message_id: string
  is_new_thread: boolean
}

function get_internal_secret(): string | undefined {
  return env.INTERNAL_INGEST_SECRET
}

function valid_payload(body: Partial<MessagesEmailInboundRequestBody>): body is MessagesEmailInboundRequestBody {
  return typeof body.message_id === 'string'
    && typeof body.from_email === 'string'
    && typeof body.to_email === 'string'
    && typeof body.subject === 'string'
    && typeof body.received_at === 'string'
    && Array.isArray(body.email_references)
    && Array.isArray(body.attachments)
}

export const POST: RequestHandler = async ({ request }) => {
  const expected = get_internal_secret()
  if (!expected)
    error(ResponseCodes.INTERNAL_SERVER_ERROR, 'INTERNAL_INGEST_SECRET not configured')

  const provided = request.headers.get('x-internal-secret')
  if (provided !== expected)
    error(ResponseCodes.UNAUTHORIZED, 'Invalid internal secret')

  const body = await request.json() as Partial<MessagesEmailInboundRequestBody>
  if (!valid_payload(body))
    error(ResponseCodes.BAD_REQUEST, 'Missing or malformed required fields')

  const from_email_lower = body.from_email.trim().toLowerCase()
  if (!/^[^\s@]+@[^\s@][^\s.@]*\.[^\s@]+$/.test(from_email_lower))
    error(ResponseCodes.BAD_REQUEST, 'Invalid from_email format')

  const db = get_shared_db()

  // Thread resolution: RFC headers → subject heuristic → new
  const { thread_id, is_new } = find_or_create_thread({
    db,
    lookup: {
      from_email: from_email_lower,
      subject: body.subject,
      in_reply_to: body.in_reply_to,
      email_references: body.email_references,
    },
  })

  const matching_user = db.prepare(
    'SELECT id FROM users WHERE email = ? COLLATE NOCASE LIMIT 1',
  ).get(from_email_lower) as { id: string } | undefined

  const message_row_id = randomUUID()
  const now = new Date().toISOString()
  const received_at_iso = body.received_at

  insert_inbound({
    db,
    thread_id,
    is_new,
    message_row_id,
    matching_user_id: matching_user?.id ?? null,
    body,
    from_email_lower,
    received_at_iso,
    now,
  })

  // Insert one message_attachments row per attachment the worker uploaded to
  // R2. The worker's attachment_id IS the R2 object key, so we store it on
  // both `id` and `storage_key`.
  for (const att of body.attachments) {
    db.prepare(`
      INSERT INTO message_attachments (
        id, message_id, filename, mimetype, size_bytes,
        content_id, disposition, storage_key,
        created_at, updated_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
      att.attachment_id,
      message_row_id,
      att.filename,
      att.mimetype,
      att.size_bytes,
      att.content_id ?? null,
      att.disposition,
      att.attachment_id,
      now,
      now,
    )
  }

  // TODO(D4-followup): admin notifications. House sends a fire-and-forget
  // ntfy push to all admins on every inbound. LD's `$lib/admins.ts` doesn't
  // have ntfy_topic columns yet — when added, fire it here.

  return json({
    ok: true,
    thread_id,
    message_id: message_row_id,
    is_new_thread: is_new,
  } satisfies MessagesEmailInboundResponseBody)
}

/** Inserts thread (when new) + message + bumps last_message_at, atomically. */
function insert_inbound({
  db,
  thread_id,
  is_new,
  message_row_id,
  matching_user_id,
  body,
  from_email_lower,
  received_at_iso,
  now,
}: {
  db: Database.Database
  thread_id: string
  is_new: boolean
  message_row_id: string
  matching_user_id: string | null
  body: MessagesEmailInboundRequestBody
  from_email_lower: string
  received_at_iso: string
  now: string
}): void {
  const txn = db.transaction(() => {
    if (is_new) {
      db.prepare(`
        INSERT INTO message_threads (
          id, subject, source, from_user_id, from_email, from_name, to_email,
          last_message_at,
          created_at, updated_at
        ) VALUES (?, ?, 'email', ?, ?, ?, ?, ?, ?, ?)
      `).run(
        thread_id,
        body.subject || null,
        matching_user_id,
        from_email_lower,
        body.from_name?.trim() || null,
        body.to_email.trim().toLowerCase(),
        received_at_iso,
        now,
        now,
      )
    } else {
      db.prepare(`
        UPDATE message_threads
        SET last_message_at = ?,
            updated_at = ?
        WHERE id = ?
      `).run(received_at_iso, now, thread_id)
    }

    db.prepare(`
      INSERT INTO messages (
        id, thread_id, author_user_id, author_kind,
        body_text, body_html,
        message_id, in_reply_to, email_references, raw_headers,
        created_at, updated_at
      ) VALUES (?, ?, ?, 'customer', ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
      message_row_id,
      thread_id,
      matching_user_id,
      body.body_text,
      body.body_html,
      body.message_id,
      body.in_reply_to,
      body.email_references.length > 0 ? body.email_references.join(' ') : null,
      body.raw_headers,
      received_at_iso,
      now,
    )
  })
  txn()
}
