import firebase_dictionaries from './firestore-data/firestore-dictionaries-prod.json'
import { generate_dictionary_inserts } from './generate-dictionary-inserts'
import type { IDictionary } from './types'

test(generate_dictionary_inserts, () => {
  const sql = generate_dictionary_inserts(firebase_dictionaries as IDictionary[])
  expect(sql.slice(0, 1000)).toMatchInlineSnapshot(`
    "INSERT INTO dictionaries ("alternate_names", "author_connection", "community_permission", "con_language_description", "coordinates", "copyright", "created_at", "created_by", "featured_image", "gloss_languages", "glottocode", "hide_living_tongues_logo", "id", "iso_639_3", "language_used_by_community", "location", "metadata", "name", "orthographies", "print_access", "public", "updated_at", "updated_by") VALUES
    ('{glossary}', 'Arabic is the third most widespread official language after English and French,[16] one of six official languages of the United Nations,[17] and the liturgical language of Islam.[18] Arabic is widely taught in schools and universities around the world and is used to varying degrees in workplaces, governments and the media.[18] During the Middle Ages, Arabic was a major vehicle of culture and learning, especially in science, mathematics and philosophy. As a result, many European languages have borrowed words from it. Arabic influence, mainly in vocabulary, is seen in"
  `)
})

test('coordinates', () => {
  const sql = generate_dictionary_inserts([
    { coordinates: { _longitude: 1, _latitude: 2 } },
    { coordinates: { longitude: 1, latitude: 2 } },
    { coordinates: { longitude: 1, latitude: 2 }, points: [{ coordinates: { latitude: 3, longitude: 4 } }] },
    { coordinates: { _longitude: 1, _latitude: 2 }, regions: [{ coordinates: [{ longitude: 1, latitude: 2 }] }] },
  ])
  expect(sql).toMatchInlineSnapshot(`
    "INSERT INTO dictionaries ("alternate_names", "author_connection", "community_permission", "con_language_description", "coordinates", "copyright", "created_at", "created_by", "featured_image", "gloss_languages", "glottocode", "hide_living_tongues_logo", "id", "iso_639_3", "language_used_by_community", "location", "metadata", "name", "orthographies", "print_access", "public", "updated_at", "updated_by") VALUES
    (null, null, null, null, '{"points":[{"coordinates":{"latitude":2,"longitude":1}}]}'::jsonb, null, null, 'de2d3715-6337-45a3-a81a-d82c3210b2a7', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'de2d3715-6337-45a3-a81a-d82c3210b2a7')
    ON CONFLICT (id) DO UPDATE SET "alternate_names" = EXCLUDED."alternate_names", "author_connection" = EXCLUDED."author_connection", "community_permission" = EXCLUDED."community_permission", "con_language_description" = EXCLUDED."con_language_description", "coordinates" = EXCLUDED."coordinates", "copyright" = EXCLUDED."copyright", "created_at" = EXCLUDED."created_at", "created_by" = EXCLUDED."created_by", "featured_image" = EXCLUDED."featured_image", "gloss_languages" = EXCLUDED."gloss_languages", "glottocode" = EXCLUDED."glottocode", "hide_living_tongues_logo" = EXCLUDED."hide_living_tongues_logo", "id" = EXCLUDED."id", "iso_639_3" = EXCLUDED."iso_639_3", "language_used_by_community" = EXCLUDED."language_used_by_community", "location" = EXCLUDED."location", "metadata" = EXCLUDED."metadata", "name" = EXCLUDED."name", "orthographies" = EXCLUDED."orthographies", "print_access" = EXCLUDED."print_access", "public" = EXCLUDED."public", "updated_at" = EXCLUDED."updated_at", "updated_by" = EXCLUDED."updated_by";
    INSERT INTO dictionaries ("alternate_names", "author_connection", "community_permission", "con_language_description", "coordinates", "copyright", "created_at", "created_by", "featured_image", "gloss_languages", "glottocode", "hide_living_tongues_logo", "id", "iso_639_3", "language_used_by_community", "location", "metadata", "name", "orthographies", "print_access", "public", "updated_at", "updated_by") VALUES
    (null, null, null, null, '{"points":[{"coordinates":{"latitude":2,"longitude":1}}]}'::jsonb, null, null, 'de2d3715-6337-45a3-a81a-d82c3210b2a7', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'de2d3715-6337-45a3-a81a-d82c3210b2a7')
    ON CONFLICT (id) DO UPDATE SET "alternate_names" = EXCLUDED."alternate_names", "author_connection" = EXCLUDED."author_connection", "community_permission" = EXCLUDED."community_permission", "con_language_description" = EXCLUDED."con_language_description", "coordinates" = EXCLUDED."coordinates", "copyright" = EXCLUDED."copyright", "created_at" = EXCLUDED."created_at", "created_by" = EXCLUDED."created_by", "featured_image" = EXCLUDED."featured_image", "gloss_languages" = EXCLUDED."gloss_languages", "glottocode" = EXCLUDED."glottocode", "hide_living_tongues_logo" = EXCLUDED."hide_living_tongues_logo", "id" = EXCLUDED."id", "iso_639_3" = EXCLUDED."iso_639_3", "language_used_by_community" = EXCLUDED."language_used_by_community", "location" = EXCLUDED."location", "metadata" = EXCLUDED."metadata", "name" = EXCLUDED."name", "orthographies" = EXCLUDED."orthographies", "print_access" = EXCLUDED."print_access", "public" = EXCLUDED."public", "updated_at" = EXCLUDED."updated_at", "updated_by" = EXCLUDED."updated_by";
    INSERT INTO dictionaries ("alternate_names", "author_connection", "community_permission", "con_language_description", "coordinates", "copyright", "created_at", "created_by", "featured_image", "gloss_languages", "glottocode", "hide_living_tongues_logo", "id", "iso_639_3", "language_used_by_community", "location", "metadata", "name", "orthographies", "print_access", "public", "updated_at", "updated_by") VALUES
    (null, null, null, null, '{"points":[{"coordinates":{"latitude":2,"longitude":1}},{"coordinates":{"latitude":3,"longitude":4}}]}'::jsonb, null, null, 'de2d3715-6337-45a3-a81a-d82c3210b2a7', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'de2d3715-6337-45a3-a81a-d82c3210b2a7')
    ON CONFLICT (id) DO UPDATE SET "alternate_names" = EXCLUDED."alternate_names", "author_connection" = EXCLUDED."author_connection", "community_permission" = EXCLUDED."community_permission", "con_language_description" = EXCLUDED."con_language_description", "coordinates" = EXCLUDED."coordinates", "copyright" = EXCLUDED."copyright", "created_at" = EXCLUDED."created_at", "created_by" = EXCLUDED."created_by", "featured_image" = EXCLUDED."featured_image", "gloss_languages" = EXCLUDED."gloss_languages", "glottocode" = EXCLUDED."glottocode", "hide_living_tongues_logo" = EXCLUDED."hide_living_tongues_logo", "id" = EXCLUDED."id", "iso_639_3" = EXCLUDED."iso_639_3", "language_used_by_community" = EXCLUDED."language_used_by_community", "location" = EXCLUDED."location", "metadata" = EXCLUDED."metadata", "name" = EXCLUDED."name", "orthographies" = EXCLUDED."orthographies", "print_access" = EXCLUDED."print_access", "public" = EXCLUDED."public", "updated_at" = EXCLUDED."updated_at", "updated_by" = EXCLUDED."updated_by";
    INSERT INTO dictionaries ("alternate_names", "author_connection", "community_permission", "con_language_description", "coordinates", "copyright", "created_at", "created_by", "featured_image", "gloss_languages", "glottocode", "hide_living_tongues_logo", "id", "iso_639_3", "language_used_by_community", "location", "metadata", "name", "orthographies", "print_access", "public", "updated_at", "updated_by") VALUES
    (null, null, null, null, '{"points":[{"coordinates":{"latitude":2,"longitude":1}}],"regions":[{"coordinates":[{"longitude":1,"latitude":2}]}]}'::jsonb, null, null, 'de2d3715-6337-45a3-a81a-d82c3210b2a7', null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'de2d3715-6337-45a3-a81a-d82c3210b2a7')
    ON CONFLICT (id) DO UPDATE SET "alternate_names" = EXCLUDED."alternate_names", "author_connection" = EXCLUDED."author_connection", "community_permission" = EXCLUDED."community_permission", "con_language_description" = EXCLUDED."con_language_description", "coordinates" = EXCLUDED."coordinates", "copyright" = EXCLUDED."copyright", "created_at" = EXCLUDED."created_at", "created_by" = EXCLUDED."created_by", "featured_image" = EXCLUDED."featured_image", "gloss_languages" = EXCLUDED."gloss_languages", "glottocode" = EXCLUDED."glottocode", "hide_living_tongues_logo" = EXCLUDED."hide_living_tongues_logo", "id" = EXCLUDED."id", "iso_639_3" = EXCLUDED."iso_639_3", "language_used_by_community" = EXCLUDED."language_used_by_community", "location" = EXCLUDED."location", "metadata" = EXCLUDED."metadata", "name" = EXCLUDED."name", "orthographies" = EXCLUDED."orthographies", "print_access" = EXCLUDED."print_access", "public" = EXCLUDED."public", "updated_at" = EXCLUDED."updated_at", "updated_by" = EXCLUDED."updated_by";
    "
  `)
})
